# Redis数据库索引（默认为0）
spring.redis:
  database: 0
  redis.host: localhost
  port: 6379
  password: redis
  pool.max-active: 8
  pool.max-wait: -1
  pool.max-idle: 8
  pool.min-idle: 0
  timeout: 0



#方式一：使用Hikarx连接池配置
spring.datasource:
  test1:
    poolName: 'test1'
    connectionTimeout: 30000
    maxLifetime: 600000
    idleTimeout: 60000
    validationTimeout: 5000
    maximumPoolSize: 100
    minimumIdle: 10
    connectionTestQuery: 'select 1'
    type: 'com.zaxxer.hikari.HikariDataSource'
    driverClassName: 'com.mysql.jdbc.Driver'
    jdbcUrl: 'jdbc:mysql://testdb1:3306/test1?useUnicode=true&characterEncoding=utf-8'
    username: root
    password: root
  test2:
    poolName: 'test2'
    connectionTimeout: 30000
    maxLifetime: 600000
    idleTimeout: 60000
    validationTimeout: 5000
    maximumPoolSize: 100
    minimumIdle: 10
    connectionTestQuery: 'select 1'
    type: 'com.zaxxer.hikari.HikariDataSource'
    driverClassName: 'com.mysql.jdbc.Driver'
    jdbcUrl: 'jdbc:mysql://testdb2:8066/test2?useUnicode=true&characterEncoding=utf-8&timeBetweenEvictionRunsMillis=3600000&minEvictableIdleTimeMillis=18000000'
    username: root
    password: root


#SysDataSourceConfig1.java===SpringBoot内置的数据源配置： 不使用tomcat连接池，而是使用hikarx连接池  --- JdbcConfig.java
# 方式二： tomcat.jdbc.pool 配置
spring:
  datasource:
    continue-on-error: false
    initialize: false
    jmx-enabled: false
    name: dataSource
    type: 'com.zaxxer.hikari.HikariDataSource'
    driver-class-name: 'com.mysql.jdbc.Driver'
    url: 'jdbc:mysql://1.1.1.1:3306/testdb1?useUnicode=true&characterEncoding=utf-8'
    username: root
    password: root
    max-active: 100
    max-idle: 8
    min-idle: 8
    test-while-idle: true
    time-between-eviction-runs-millis: 1
    validation-query: 'SELECT 1'
    hikari:
      connection-test-query: 'SELECT 1'
      connection-timeout: 60000
      maximum-pool-size: 200
      allow-pool-suspension: false
      max-active: 122
      max-idle: 21
      min-idle: 82
      connection-init-sql: 'select 1'
  second-datasource:
    driver-class-name: 'com.mysql.jdbc.Driver'
    url: 'jdbc:mysql://2.2.2.2:3306/testdb1?useUnicode=true&characterEncoding=utf-8&autoReconnect=true'
    username: mysql
    password: mysql
    max-active: 200
    max-idle: 10
    min-idle: 8
    test-while-idle: true
    time-between-eviction-runs-millis: 1
    validation-query: 'SELECT 1'





#方式三：自定义的数据源配置  --- DataSourceConfig.java
mysql.spring.datasource:
  driver-class-name: 'com.mysql.jdbc.Driver'
  url: 'jdbc:mysql://localhost:3306/taotao?useUnicode=true&characterEncoding=utf-8'
  username: root
  password: 123456
#连接池配置
  max-active: 100
  min-idle: 8
